### PR TITLE
Upgraded the BlockBreadcrumbs plugin to work with EPiServer CMS 10

### PR DESCRIPTION
**Pull request by stgaup**
I have upgraded the TestWeb and the Plugin to EPiServer 10.
Also fixed the breaking change from episerver, please check Issues.

### CODE REVIEW

**Comment by stgaup** [comment]
Please note that the plugin will not work for previous versions of EPiServer once this change has been pulled.

**Comment by skjelbek** [comment]
See my comment on the related issue.

PS: You also need to bump up the dependancy of `EPiServer.CMS.Core` to `10.0.1` in the `BlockBreadcrumbs.nuspec` (hidden file in the BlockBreadcrumbs project).

**Comment by skjelbek** [comment]
Due to the lack of response - and the urge to make the package compatible with EPiServer 10.0.1 - I just did the suggested change myself and merged the PR. I've tested it, and everything seems to work well.

**Comment by stgaup** [comment]
Hi, and thanks! 
Sorry for not responding in a timely manner.

**Pull request merged**
